### PR TITLE
Multiple issue fixes

### LINKED ISSUE #81: eventstore/query: check slice type on Find()
Check that return slice for the query is of the proper type of the model.

### LINKED ISSUE #89: storethread: retries on failed fetchs
Implement some mechanism to do some minimum retries before considering a network fech of data fatal (i.e: the body of an `Event`).

### LINKED ISSUE #97: store: enforce model/type registration to be pointers
Registered models/types should be pointers, since the store will autogenereate IDs. If it wasn't a pointer, the client couldn't see the generated ID without making some query about inserted data (which can't be by ID which is weird).

So, feels like error prone to accept non-pointer type instances.

### LINKED ISSUE #111: general: check for Close() ignored errors
Make them explicit and let the caller decide if ignore them.

### PR DESCRIPTION
**Pull request by jsign**
Not heavy stuff in this PR.

- Fixes #89 
- Fixes #81 
- Fixes #111
- Fixes #97
- Added some extra missing tests thanks to linter reporting unused var 
- Fixes some lint checks.

Also fixes tests that were broken in master due to a previous merged PR. All working now.

Extra code comments to help review.

### CODE REVIEW

File: eventstore/manager.go [hunk 1]
```diff
@@ -105,11 +105,18 @@ func (m *Manager) GetStore(id uuid.UUID) *Store {
 }
 
 // Close all the in-mem stores.
-func (m *Manager) Close() (err error) {
+func (m *Manager) Close() error {
```
Comment (jsign) [inline eventstore/manager.go]: Decided the most reasonable thing is try to continue closing things even of something fails in the middle.
Each failing thing is logged, and the error returned is the last error that happened.
I think this may be better than just returning on first error since would leave other things open that might be closable.

File: eventstore/query.go [hunk 2]
```diff
@@ -69,8 +72,11 @@ func (q *Query) OrderByDesc(field string) *Query {
 // pointers with the correct model type. If the slice isn't empty, will be emptied.
 func (t *Txn) Find(res interface{}, q *Query) error {
 	valRes := reflect.ValueOf(res)
-	if valRes.Kind() != reflect.Ptr || valRes.Elem().Kind() != reflect.Slice {
-		panic("result should be a slice")
+	if valRes.Kind() != reflect.Ptr || // Should be a pointer
```
Comment (jsign) [inline eventstore/query.go]: The `res` parameter can't be anything. It should be a concrete type for the query considering the model being queried. Now it checks that is what's expected... since if that check doesn't hold, the code will panic in line: `		resSlice = reflect.Append(resSlice, unsorted[i])`

TBH, these checks has some cost... nothing is free in particular with refect. If the client is sending the wrong thing, maybe it should panic because that's a serious error here. Shouldn't be expected by any means... so maybe these checks can be deleted and make the client responsible to use it correctly.

File: eventstore/query_jsonmode_test.go [hunk 3]
```diff
@@ -97,8 +97,8 @@ var (
 			name:   "EqByTitle1",
```
Comment (jsign) [inline eventstore/query_jsonmode_test.go]: Fixes the tests broken in master.

File: eventstore/query_test.go [hunk 4]
```diff
@@ -142,6 +143,16 @@ func TestInvalidSortField(t *testing.T) {
 	}
 }
 
+func TestInvalidSliceType(t *testing.T) {
```
Comment (jsign) [inline eventstore/query_test.go]: Extra test to check the new feature of checking that received slice for `Find` controls that has the right type for the queried Model.

File: eventstore/store.go [hunk 5]
```diff
@@ -213,6 +215,11 @@ func (s *Store) Register(name string, defaultInstance interface{}) (*Model, erro
 	s.lock.Lock()
 	defer s.lock.Unlock()
 
+	diType := reflect.TypeOf(defaultInstance)
```
Comment (jsign) [inline eventstore/store.go]: Check that the registered default instance of the model has a correct type.
They should always be pointers to structs. e.g. `m.Register("Person", &Person{})`.

File: eventstore/storethread.go [hunk 6]
```diff
@@ -101,7 +102,7 @@ func (a *singleThreadAdapter) threadToStore(wg *sync.WaitGroup) {
 			ctx, cancel := context.WithTimeout(context.Background(), fetchEventTimeout)
 			event, err := threadcbor.EventFromRecord(ctx, a.api, rec.Value())
 			if err != nil {
-				block, err := rec.Value().GetBlock(ctx, a.api)
+				block, err := a.getBlockWithRetry(ctx, rec.Value(), 3, time.Millisecond*500)
```
Comment (jsign) [inline eventstore/storethread.go]: Fixed 3 retries with 500ms expbackoff. Can eventually be configured with opts

File: eventstore/storethread.go [hunk 7]
```diff
@@ -158,3 +159,17 @@ func (a *singleThreadAdapter) storeToThread(wg *sync.WaitGroup) {
...
+func (a *singleThreadAdapter) getBlockWithRetry(ctx context.Context, rec thread.Record, cantRetries int, backoffTime time.Duration) (format.Node, error) {
+	var err error
+	for i := 1; i <= cantRetries; i++ {
+		n, err := rec.GetBlock(ctx, a.api)
+		if err == nil {
+			return n, nil
+		}
+		log.Warningf("error when fetching block %s in retry %d", rec.Cid(), i)
+		time.Sleep(backoffTime)
+		backoffTime *= 2
```
Comment (jsign) [inline eventstore/storethread.go]: exponential backoff

File: eventstore/util.go [hunk 8]
```diff
@@ -14,7 +14,7 @@ import (
 	host "github.com/libp2p/go-libp2p-core/host"
 	"github.com/libp2p/go-libp2p-core/peer"
 	dht "github.com/libp2p/go-libp2p-kad-dht"
-	peerstore "github.com/libp2p/go-libp2p-peerstore"
+	"github.com/libp2p/go-libp2p-core/peerstore"
```
Comment (jsign) [inline eventstore/util.go]: Deprecated import

File: examples/chat/main.go [hunk 9]
```diff
@@ -55,32 +55,32 @@ const (
...
-					"Time": {
-						"type": "integer"
-					}
-				},
-				"additionalProperties": false,
-				"type": "object"
-			}
-		}
-	}`
+	// schema = `{
```
Comment (jsign) [inline examples/chat/main.go]: `schema` was unused. Preferred to comment it instead of deleting it to have a second opinion if this was expected?

**Comment by jsign** [comment]
Maybe @sanderpick  might worth taking a look at some PR comments. Mostly the `schema` unused var that I'm not sure had some missing intention.

Not a hurry at all... just to not be missing something.
